export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const ADDPRODUCTS = "ADDPRODUCTS";
export const ADDPRODUCTSRESPONSE = "ADDPRODUCTSRESPONSE";
export const GETALLPRODUCTS = "GETALLPRODUCTS";
export const GETALLPRODUCTSRESPONSE = "GETALLPRODUCTSRESPONSE";