export { default as Manutd_logo } from '../../components/assets/team_logo/ManUtd_logo.png'
export { default as Barcelona_logo } from '../../components/assets/team_logo/Barcelona_logo.png'
export {default as RealMadrid_logo} from '../../components/assets/team_logo/Real-Madrid_logo.png'
export {default as PSG_logo} from '../../components/assets/team_logo/PSG_logo.png'
export {default as Arsenal_logo} from '../../components/assets/team_logo/Arsenal_logo.png'
export {default as Liverpool_logo} from '../../components/assets/team_logo/Liverpool_logo.png'
export {default as Dortmund_logo} from '../../components/assets/team_logo/Dortmund_logo.png'
export {default as Benfica_logo} from '../../components/assets/team_logo/Benfica_logo.png'
export {default as Juventus_logo} from '../../components/assets/team_logo/Juventus_logo.png'
export {default as Chelsea_logo} from '../../components/assets/team_logo/Chelsea_logo.png'
export {default as Intermilan_logo} from '../../components/assets/team_logo/Intermilan_logo.png'