export { default as Manutd_logo } from '../../components/assets/team_logo/ManUtd_logo.png'
export { default as Barcelona_logo } from '../../components/assets/team_logo/Barcelona_logo.png'
export {default as RealMadrid_logo} from '../../components/assets/team_logo/Real-Madrid_logo.png'
export {default as PSG_logo} from '../../components/assets/team_logo/PSG_logo.png'
export {default as Arsenal_logo} from '../../components/assets/team_logo/Arsenal_logo.png'
export {default as Liverpool_logo} from '../../components/assets/team_logo/Liverpool_logo.png'
export {default as Dortmund_logo} from '../../components/assets/team_logo/Dortmund_logo.png'
export {default as Benfica_logo} from '../../components/assets/team_logo/Benfica_logo.png'
export {default as Juventus_logo} from '../../components/assets/team_logo/Juventus_logo.png'
export {default as Chelsea_logo} from '../../components/assets/team_logo/Chelsea_logo.png'
export {default as Intermilan_logo} from '../../components/assets/team_logo/Intermilan_logo.png'
export {default as Argentina_logo} from '../../components/assets/international_logo/Argentina_logo.png'
export {default as Brazil_logo} from '../../components/assets/international_logo/Brazil_logo.png'
export {default as England_logo} from '../../components/assets/international_logo/England_logo.png'
export {default as France_logo} from '../../components/assets/international_logo/France_logo.png'
export {default as Germany_logo} from '../../components/assets/international_logo/Germany_logo.png'
export {default as Italy_logo} from '../../components/assets/international_logo/Italy_logo.png'
export {default as Portugal_logo} from '../../components/assets/international_logo/Portugal_logo.png'
export {default as Spain_logo} from '../../components/assets/international_logo/Spain_logo.png'
export {default as Crotia_logo} from '../../components/assets/international_logo/Crotia_logo.png'
export {default as Nezerlands_logo} from '../../components/assets/international_logo/Nezerlands_logo.png'
export {default as Egypt_logo} from '../../components/assets/international_logo/Egypt_logo.png'
export {default as Senegal_logo} from '../../components/assets/international_logo/Senegal_logo.png'
